version: "3.3"
services:
  dynamodb-local:
    image: sls-cli
    container_name: dynamodb-local
    volumes:
      - .:/app
      # - .dynamodb:/data
    command: ["npx", "serverless", "dynamodb", "start"]
    ports:
      - 8000:8000 # 外部ポート: docker のポート
  wsgi:
    image: sls-cli
    container_name: wsgi
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws
    command: ["npx", "serverless", "wsgi", "serve", "--host", "0.0.0.0"]
    ports:
      - 5000:5000
